info:
  title: Love Tomato
  author: Hang
  url: 

defaults:
  favicon: https://savemyblogpic-1311313070.cos.ap-chengdu.myqcloud.com/blogpicture/IMG_7334.jpeg
  logo: https://savemyblogpic-1311313070.cos.ap-chengdu.myqcloud.com/blogpicture/IMG_7334.jpeg
  avatar: https://savemyblogpic-1311313070.cos.ap-chengdu.myqcloud.com/blogpicture/IMG_7334.jpeg

colors:
  primary: "#A31F34"
  secondary: 

global:
  fonts:
    chinese: 
      enable: true # Whether to enable custom chinese fonts
      family: 
      url:  # Font URL to CSS file
  
    english: 
      enable: true # Whether to enable custom english fonts
      family: 
      url:  # Font URL to CSS file
  
  content_max_width: 1000px
  sidebar_width: 210px
  
  hover:
    shadow: true # shadow effect
    scale: false # scale effect
  
  scroll_progress:
    bar: true # progress bar
    percentage: false # percentage

  website_counter:
    url: https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js 
    enable: true # enable website counter or not
    site_pv: true # site page view
    site_uv: true # site unique visitor
    post_pv: false # post page view
  # Whether to enable single page experience (using swup). See https://swup.js.org/. similar to pjax
  single_page: true
  
  preloader: false
  open_graph: true
  google_analytics:
    enable: false # Whether to enable Google Analytics
    id:  # Google Analytics Measurement ID
    
fontawesome: # Pro v6.2.1
  thin: true
  light: true
  duotone: true
  sharp_solid: true

home_banner:
  enable: true
  style: fixed # static or fixed
  image: 
    light: https://savemyblogpic-1311313070.cos.ap-chengdu.myqcloud.com/blogpicture/%E5%B9%BB%E7%81%AF%E7%89%87%2016_9%20-%207@4x.png
    dark: https://savemyblogpic-1311313070.cos.ap-chengdu.myqcloud.com/blogpicture/jamesgilleard.jpg

  title: 👀
  subtitle:
    text: [] 
    typing_speed: 100 # Typing speed (ms)
    backing_speed: 80 # Backing speed (ms)
    starting_delay: 500 # Start delay (ms)
    backing_delay: 1500 # Backing delay (ms)
    loop: true # Whether to loop
    smart_backspace: true # Whether to smart backspace

  text_color: 
    light: "#fff" # light mode
    dark: "#d1d1b6" # dark mode
  text_style: 
    title_size: 2.8 rem
    subtitle_size: 1.5rem
    line_height: 1.2
  
  custom_font: 
    enable: false
    family: 
    url:

  social_links:
    enable: false
    links:
      github:
      instagram:
      zhihu:
      twitter:
      email:

    # Social links with QRcode drawers
    qrs:
      weixin: https://savemyblogpic-1311313070.cos.ap-chengdu.myqcloud.com/blogpicture/iShot_2023-12-20_16.16.37.png
      # ...... # you can add more

navbar:
  auto_hide: false
  color:
    left: "#f78736" #left side 
    right: "#367df7"  #right side
    transparency: 35 #percent (10-99)
  links:
    Home: 
      path: / 
      icon: fa-regular fa-house 

    categories:
      path: /categories
      icon: fa-light fa-rectangle-list

    Archives: 
      path: /archives 
      icon: fa-regular fa-archive
    
    About:
      path: /about
      icon: fa-regular fa-address-card


    看什么:
      icon: fa-regular fa-eyes
      submenus:
        书单: /books
        观影: /movies

    # About: 
    #   icon: fa-regular fa-user
    #   submenus:
    #     Me: /about
    #     Github: https://github.com/EvanNotFound/hexo-theme-redefine
    #     Blog: https://ohevan.com
    #     Friends: /friends
    # Links: 
    #   icon: fa-regular fa-link
    #   submenus:
    #     Link1: /link1
    #     Link2: /link2
    #     Link3: /link3
    # ...... # you can add more

  # Navbar search (local search). Requires hexo-generator-searchdb (npm i hexo-generator-searchdb). See https://github.com/theme-next/hexo-generator-searchdb
  search:
    enable: false
    preload: false

home:
  sidebar:
    enable: true 
    position: left # Sidebar position. left, right
    first_item: info # menu, info
    announcement: 指路牌
    links:
      设计:
        icon: fa-regular fa-hashtag
        path: https://woooooo.cn/categories/%E8%AE%BE%E8%AE%A1/
      
      阅读:
        icon: fa-regular fa-hashtag
        path: https://woooooo.cn/categories/%E9%98%85%E8%AF%BB/

      旅行:
        icon: fa-regular fa-hashtag
        path: https://woooooo.cn/categories/%E6%97%85%E8%A1%8C/

      思考:
        icon: fa-regular fa-hashtag
        path: https://woooooo.cn/categories/%E6%80%9D%E8%80%83/

      


  # Article date format
  article_date_format: auto # auto, relative, YYYY-MM-DD, YYYY-MM-DD HH:mm:ss etc.
  categories:
    enable: true  # Whether to enable
    limit: 3 # Max number of categories to display
 
  tags:
    enable: true  # Whether to enable
    limit: 3  # Max number of tags to display

articles:
  style:
    font_size: 16px 
    line_height: 1.8
    image_border_radius: 8px 
    image_alignment: center
    image_magin: 1rem auto 1rem
    image_caption: false
    link_icon: false
    title_alignment: left 
  # Word count. Requires hexo-wordcount (npm install hexo-wordcount). See https://github.com/willin/hexo-wordcount
  word_count:
    enable: true # Whether to enable
    count: true # Whether to display word count
    min2read: true # Whether to display reading time
  
  author_label: 
    enable: true # Whether to enable
    auto: false # Whether to automatically add author label, e.g. Lv1, Lv2, Lv3...
    list: [UE designer]
  
  code_block:
    copy: true # Whether to enable code block copy button
    style: mac # mac | simple
    font: # Custom font
      enable: false # Whether to enable
      family: # Font family
      url: # Font URL to CSS file
  
  toc:
    enable: true
    max_depth: 3
    number: false
    expand: true
    init_open: true
  
  copyright:
    enable: false
    default: cc_by_nc_sa # Default license, can be cc_by_nc_sa, cc_by_nd, cc_by_nc, cc_by_sa, cc_by, all_rights_reserved, public_domain
  
  lazyload: true

  # Article recommendation. Requires nodejieba (npm install nodejieba). Transplanted from hexo-theme-volantis.
  recommendation:
    enable: true
    title: 推荐阅读
    limit: 3
    mobile_limit: 2
    placeholder: https://savemyblogpic-1311313070.cos.ap-chengdu.myqcloud.com/blogpicture/_.jpg
    # Skip directory
    skip_dirs: []

comment:
  enable: false
  system: waline
  config:
    # Waline comment system. See https://waline.js.org/
    waline:
      serverUrl: 
      lang: zh-CN 
      emoji: [] # Waline emojis, see https://waline.js.org/guide/features/emoji.html
      recaptchaV3Key: wasd # Google reCAPTCHA v3 key. See https://waline.js.org/reference/client/props.html#recaptchav3key
      turnstileKey: # Turnstile key. See https://waline.js.org/reference/client/props.html#turnstilekey

footer:
  runtime: false # show website running time or not
  icon: '<i class="fa-solid fa-heart fa-beat" style="--fa-animation-duration: 0.5s; color: #f54545"></i>'
  start: 2023/1/17 11:45:14
  customize:
  # ICP record number. See https://beian.miit.gov.cn/
  icp:
    enable: false # Whether to enable
    number: # ICP record number
    url: # ICP record url


inject:
  enable: false
  # Inject custom head html code
  head: 
    -
    -
  # Inject custom footer html code
  footer:
    -
    -

plugins:
  # RSS feed. Requires hexo-generator-feed (npm i hexo-generator-feed). See https://github.com/hexojs/hexo-generator-feed
  feed:
    enable: true # Whether to enable
  aplayer:
    enable: true
    type: fixed # fixed, mini
    audios:
      - name: 【钢琴】渔光曲
        artist: 昼夜
        url: https://savemyblogpic-1311313070.cos.ap-chengdu.myqcloud.com/music/%E3%80%90%E6%98%BC%E5%A4%9C%E3%80%91%E6%B8%94%E5%85%89%E6%9B%B2%20-%20001%20-%20%E3%80%90%E6%98%BC%E5%A4%9C%E3%80%91%E6%B8%94%E5%85%89%E6%9B%B2.mp3
        cover: https://savemyblogpic-1311313070.cos.ap-chengdu.myqcloud.com/blogpicture/yuguangqu.jpg
      - name: 梁祝
        artist: 吕思清
        url: https://savemyblogpic-1311313070.cos.ap-chengdu.myqcloud.com/music/%E6%A2%81%E7%A5%9D.MP3
        cover: https://savemyblogpic-1311313070.cos.ap-chengdu.myqcloud.com/blogpicture/iShot_2023-12-20_16.10.11.png
      - name: Merry Christmas Mr. Lawrence
        artist: 坂本龍一
        url: https://savemyblogpic-1311313070.cos.ap-chengdu.myqcloud.com/music/%E3%80%90%E7%BA%AA%E5%BF%B5%EF%BD%9C%E5%9D%82%E6%9C%AC%E9%BE%99%E4%B8%80%E3%80%91%E7%99%BE%E4%B8%87%E7%BA%A7%E5%BD%95%E9%9F%B3%E6%A3%9A%E5%90%AC%E3%80%8AMerry%20Christmas%20Mr.%20Lawrence%E3%80%8B%E5%9C%A3%E8%AF%9E%E5%BF%AB%E4%B9%90%EF%BC%8C%E5%8A%B3%E4%BC%A6%E6%96%AF%E5%85%88%E7%94%9F-%E3%80%8A1996%E3%80%8B%E3%80%90Hi-Res%E3%80%91%20-%20001%20-%20%E3%80%90%E7%BA%AA%E5%BF%B5%EF%BD%9C%E5%9D%82%E6%9C%AC%E9%BE%99%E4%B8%80%E3%80%91%E7%99%BE%E4%B8%87%E7%BA%A7%E5%BD%95%E9%9F%B3%E6%A3%9A%E5%90%AC%E3%80%8AMerry%20Christmas%20Mr.%20Lawr%E2%80%A6.mp3
        cover: https://savemyblogpic-1311313070.cos.ap-chengdu.myqcloud.com/blogpicture/iShot_2023-12-20_16.16.37.png

  # Mermaid JS. Requires hexo-filter-mermaid-diagrams (npm i hexo-filter-mermaid-diagrams). See https://mermaid.js.org/
  mermaid:
    enable: false # enable mermaid or not
    version: "9.3.0" # default v9.3.0
#
page_templates:
  friends_column: 2
  tags_style: blur # blur, cloud


cdn:
  enable: true
  provider: aliyun # staticfile, bootcdn, cdnjs, jsdelivr, unpkg, custom
  # Custom CDN URL
  # format example: https://cdn.custom.com/hexo-theme-redefine/${version}/source/${path}
  # The ${path} must be in the source folder of the theme
  custom_url: 

developer:
  enable: false

